execute:
  script:
    - echo "I succeed quickly, this text was changed"


failing_job:
  script:
    - echo "I will also succeed now"
    - sleep 15
    - exit 0
    
gpu_test:
  image: nvidia/cuda:11.6.0-devel-ubuntu20.04
  script:
    - nvcc vector_add.cu -o vector_add
    - ./vector_add
