execute:
  script:
    - echo "I succeed quickly"
    - sleep 30
    - echo "Done"

long_job:
  script:
    - echo "I will also succeed now"
    - sleep 120
    - echo "done"

job_three:
  script:
    - echo "I will fail"
    - sleep 15
    - exit 1
