gpu_test:
  image: nvidia/cuda:11.5.1-devel-ubuntu18.04
  tags:
  - docker-gpu-nvidia
  script:
    - echo $PATH
    - apt update 
    - apt-get -y install git
    - git clone $CLONE_URL src
    - cd src
    - git checkout $HEAD_SHA
    - cd ..
    - ls src
    - nvcc src/helloworld.cu -o helloworld
    - ./helloworld
