execute:
  script:
    - echo "I succeed quickly, this text was changed"


failing_job:
  script:
    - echo "I will also succeed now"
    - sleep 15
    - exit 0
    
gpu_test:
  image: nvidia/cuda:11.6.0-devel-ubuntu20.04
  script:
    - apt update 
    - apt-get install git
    - git clone $CLONE_URL src
    - nvcc src/helloworld.cu -o helloworld
    - ./helloworld
