execute:
  script:
    - echo "I succeed quickly"
    - sleep 5
    - echo "Done" > output.txt

  artifacts:
  paths:
    - output.txt

long_job:
  script:
    - echo "I will also succeed now"
    - sleep 10
    - echo "done"

